# Generated by Django 2.1 on 2019-09-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='Genero',
            new_name='GeneroMascota',
        ),
    ]
