# Generated by Django 2.1 on 2019-09-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
    ]
