# Generated by Django 2.1 on 2019-09-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0002_auto_20190918_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecita',
            name='ExamenMascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.ExamenMascota'),
        ),
        migrations.AlterField(
            model_name='detallecita',
            name='Medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Medicamento'),
        ),
    ]
