# Generated by Django 2.1 on 2019-09-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0002_auto_20190917_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'permissions': (('is_usuario', 'Is Usuario'),)},
        ),
    ]
