# Generated by Django 2.1 on 2019-09-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0003_auto_20190917_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'permissions': (('is_usuario', 'Is Usuario'), ('is_admin', 'Is Admin'), ('is_doctor', 'Is Doctor'))},
        ),
    ]
