# Generated by Django 2.1 on 2019-09-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0004_auto_20190917_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='TipoExamen',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examen',
            name='Nombre',
            field=models.CharField(max_length=500),
        ),
    ]
