# Generated by Django 2.1 on 2019-09-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0016_auto_20190913_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='Genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Genero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Genero'),
        ),
    ]
