# Generated by Django 2.1 on 2019-09-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0005_auto_20190911_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='Celular',
            field=models.CharField(max_length=45),
        ),
    ]
