# Generated by Django 2.1 on 2019-09-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0007_auto_20190911_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observacion', models.CharField(max_length=50)),
                ('Citas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Citas')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('FechaNacimiento', models.DateField()),
                ('Genero', models.CharField(default='', max_length=45)),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Cliente')),
                ('HistoriaCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.HistoriaCliente')),
                ('Raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Raza')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoClinico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultado', models.CharField(max_length=45)),
                ('ExamenMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.ExamenMascota')),
            ],
        ),
        migrations.AddField(
            model_name='detallecita',
            name='ExamenMascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.ExamenMascota'),
        ),
        migrations.AddField(
            model_name='detallecita',
            name='Medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Medicamento'),
        ),
        migrations.AddField(
            model_name='citas',
            name='Mascotas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Mascotas'),
        ),
        migrations.AddField(
            model_name='citas',
            name='Medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Medico'),
        ),
    ]
