# Generated by Django 2.1 on 2019-09-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0013_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Genero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Genero'),
        ),
    ]
