# Generated by Django 2.1 on 2019-09-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VeteSoft', '0015_auto_20190913_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='Genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VeteSoft.Genero'),
        ),
    ]
